// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdfhrl5O1YfdhevgxNZjsG520pJXvMZwU',
    appId: '1:1011480770772:web:b2ac76e0487ae94b9a2341',
    messagingSenderId: '1011480770772',
    projectId: 'universe-88299',
    authDomain: 'universe-88299.firebaseapp.com',
    storageBucket: 'universe-88299.firebasestorage.app',
    measurementId: 'G-YD91W3SQT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA38V7XAtnbxowzghld3EHR4nognohkbPA',
    appId: '1:1011480770772:android:3c8e74c28bfbdb4d9a2341',
    messagingSenderId: '1011480770772',
    projectId: 'universe-88299',
    storageBucket: 'universe-88299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAumw1XS8mippkIrEs1X2CdXyW6yFoq978',
    appId: '1:1011480770772:ios:c061b1afa5cd8c189a2341',
    messagingSenderId: '1011480770772',
    projectId: 'universe-88299',
    storageBucket: 'universe-88299.firebasestorage.app',
    iosBundleId: 'com.example.uviverseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAumw1XS8mippkIrEs1X2CdXyW6yFoq978',
    appId: '1:1011480770772:ios:c061b1afa5cd8c189a2341',
    messagingSenderId: '1011480770772',
    projectId: 'universe-88299',
    storageBucket: 'universe-88299.firebasestorage.app',
    iosBundleId: 'com.example.uviverseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdfhrl5O1YfdhevgxNZjsG520pJXvMZwU',
    appId: '1:1011480770772:web:9b1dcd6b31a40aac9a2341',
    messagingSenderId: '1011480770772',
    projectId: 'universe-88299',
    authDomain: 'universe-88299.firebaseapp.com',
    storageBucket: 'universe-88299.firebasestorage.app',
    measurementId: 'G-8P75RS4414',
  );

}